version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=prueba_tecnica
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes: 
  postgres_data:
    external: true
    